"""init

Revision ID: 3e1b3668729b
Revises:
Create Date: 2025-05-11 12:19:45.475087

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e1b3668729b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trackers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tracker_type", sa.String(length=50), nullable=False),
        sa.Column("yandex_cloud_id", sa.String(length=50), nullable=True),
        sa.Column("yandex_org_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trackers_id"), "trackers", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("avatar_url", sa.String(length=255), nullable=True),
        sa.Column("yandex_id", sa.Integer(), nullable=False),
        sa.Column("yandex_token", sa.String(length=500), nullable=True),
        sa.Column("yandex_token_expires", sa.DateTime(), nullable=True),
        sa.Column("yandex_refresh_token", sa.String(length=500), nullable=True),
        sa.Column("current_tracker_id", sa.Integer(), nullable=True),
        sa.Column("cloud_id", sa.String(length=50), nullable=True),
        sa.Column("org_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_tracker_id"],
            ["trackers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("yandex_id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_trackers_id"), table_name="trackers")
    op.drop_table("trackers")
    # ### end Alembic commands ###
