"""team sprint report

Revision ID: 8cf6cf1f96b7
Revises: da3bc284c639
Create Date: 2025-05-12 20:16:17.545441

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8cf6cf1f96b7"
down_revision = "da3bc284c639"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_sprint_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tracker_id", sa.Integer(), nullable=False),
        sa.Column("sprint_id", sa.Integer(), nullable=False),
        sa.Column("sprint_start_date", sa.Date(), nullable=False),
        sa.Column("sprint_end_date", sa.Date(), nullable=False),
        sa.Column("employee_stats", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tracker_id"],
            ["trackers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracker_id", "sprint_id", name="_tracker_sprint_uc"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_sprint_reports")
    # ### end Alembic commands ###
