"""sprint report

Revision ID: da3bc284c639
Revises: 2b45016c1dc7
Create Date: 2025-05-12 19:36:29.422512

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "da3bc284c639"
down_revision = "2b45016c1dc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sprint_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tracker_id", sa.Integer(), nullable=False),
        sa.Column("sprint_id", sa.Integer(), nullable=False),
        sa.Column("sprint_name", sa.String(), nullable=False),
        sa.Column("sprint_start_date", sa.Date(), nullable=False),
        sa.Column("sprint_end_date", sa.Date(), nullable=False),
        sa.Column("story_points_closed", sa.Float(), nullable=False),
        sa.Column("tasks_completed", sa.Integer(), nullable=False),
        sa.Column("deadlines_missed", sa.Integer(), nullable=False),
        sa.Column("average_task_completion_time", sa.Float(), nullable=False),
        sa.Column("activity_analysis", sa.String(), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id", "tracker_id"],
            ["user_tracker_roles.user_id", "user_tracker_roles.tracker_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sprint_report_user_tracker",
        "sprint_reports",
        ["user_id", "tracker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sprint_report_user_tracker", table_name="sprint_reports")
    op.drop_table("sprint_reports")
    # ### end Alembic commands ###
